micronaut:
  application:
    name: email

datasources:
  default:
    url: jdbc:postgresql://localhost:5434/email
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update

kafka:
  bootstrap:
    servers: localhost:9092
  topics:
    email: email
