micronaut:
  application:
    name: contaDigital
  server.port: 8081

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/contadigital
    driverClassName: org.postgresql.Driver
    username: contadigital
    password: 12345
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
