micronaut:
  data:
    pageable:
      max-page-size: 50
      default-page-size: 20

  application:
    name: extrato
datasources:
  default:
    url: jdbc:postgresql://localhost:5433/transacao
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
